In [12]:
import polars as pl
import pandas as pd

In [13]:
test = pd.read_csv('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/Elia XBCRM Data-2026-10-01.csv')

In [14]:
test

,unit_name,ean_code,date_time,date,year,month,day,time_period,measurement_mw,fcr_capacity_mw,contracted_afrr_up_mw,contracted_afrr_down_mw,delivered_afrr_up_mwh,delivered_afrr_down_mwh,contracted_mfrr_up_mw,contracted_mfrr_down_mw,delivered_mfrr_up_mwh,delivered_mfrr_down_mwh,delivered_rd_down_mwh
0,CCC1 MBT380,871686700000006926,2026-08-01 00:00:00,2026-08-01,2026,8,1,00:00-00:15,-255.163000,4,0.0,0.0,0,0,0,0,0,0,0.0
1,CCC1 MBT380,871686700000006926,2026-08-01 00:15:00,2026-08-01,2026,8,1,00:15-00:30,-253.908000,4,0.0,0.0,0,0,0,0,0,0,0.0
2,CCC1 MBT380,871686700000006926,2026-08-01 00:30:00,2026-08-01,2026,8,1,00:30-00:45,-254.058333,4,0.0,0.0,0,0,0,0,0,0,0.0
3,CCC1 MBT380,871686700000006926,2026-08-01 00:45:00,2026-08-01,2026,8,1,00:45-01:00,-254.851333,4,0.0,0.0,0,0,0,0,0,0,0.0
4,CCC1 MBT380,871686700000006926,2026-08-01 01:00:00,2026-08-01,2026,8,1,01:00-01:15,-255.624333,4,0.0,0.0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11899,CCC4 MBT150,871688520000000933,2026-08-31 22:45:00,2026-08-31,2026,8,31,22:45-23:00,-431.057000,1,0.0,0.0,0,0,0,0,0,0,0.0
11900,CCC4 MBT150,871688520000000933,2026-08-31 23:00:00,2026-08-31,2026,8,31,23:00-23:15,-433.628333,1,0.0,0.0,0,0,0,0,0,0,0.0
11901,CCC4 MBT150,871688520000000933,2026-08-31 23:15:00,2026-08-31,2026,8,31,23:15-23:30,-422.984667,1,0.0,0.0,0,0,0,0,0,0,0.0
11902,CCC4 MBT150,871688520000000933,2026-08-31 23:30:00,2026-08-31,2026,8,31,23:30-23:45,-382.520667,1,0.0,0.0,0,0,0,0,0,0,0.0
11903,CCC4 MBT150,871688520000000933,2026-08-31 23:45:00,2026-08-31,2026,8,31,23:45-24:00,-374.745000,1,0.0,0.0,0,0,0,0,0,0,0.0

In [15]:
test = pl.from_pandas(test)

In [16]:
agg = test.select(['date_time', 'delivered_afrr_up_mwh', 'delivered_afrr_down_mwh']).group_by(pl.col('date_time')).sum().sort(pl.col('date_time'))

In [17]:
agg

shape: (2_976, 3)
┌─────────────────────┬───────────────────────┬─────────────────────────┐
│ date_time           ┆ delivered_afrr_up_mwh ┆ delivered_afrr_down_mwh │
│ ---                 ┆ ---                   ┆ ---                     │
│ str                 ┆ i64                   ┆ i64                     │
╞═════════════════════╪═══════════════════════╪═════════════════════════╡
│ 2026-08-01 00:00:00 ┆ 0                     ┆ 0                       │
│ 2026-08-01 00:15:00 ┆ 0                     ┆ 0                       │
│ 2026-08-01 00:30:00 ┆ 0                     ┆ 0                       │
│ 2026-08-01 00:45:00 ┆ 0                     ┆ 0                       │
│ 2026-08-01 01:00:00 ┆ 0                     ┆ 0                       │
│ …                   ┆ …                     ┆ …                       │
│ 2026-08-31 22:45:00 ┆ 0                     ┆ 0                       │
│ 2026-08-31 23:00:00 ┆ 0                     ┆ 0                       │
│ 2026-08-31 23:15:00 ┆ 0                     ┆ 0                       │
│ 2026-08-31 23:30:00 ┆ 0                     ┆ 0                       │
│ 2026-08-31 23:45:00 ┆ 0                     ┆ 0                       │
└─────────────────────┴───────────────────────┴─────────────────────────┘